### ISSUE TITLE
Wrongly counted PIN errors

### ISSUE THREAD

**Issue by msirringhaus** [Nitrokey/fido-authenticator#7] opened 2022-12-19 15:21 UTC
When entering a wrong PIN twice and then a valid one, NK3 still returns `PinAuthBlocked`, even though it should succeed and reset the internal counter.
Looking [here](https://github.com/Nitrokey/fido-authenticator/blob/main/src/ctap2.rs#L786), it seems the counter is decremented every time, no matter if the current PIN is correct or not (assuming I'm looking in the right place).
Shouldn't it be decremented only [here](https://github.com/Nitrokey/fido-authenticator/blob/main/src/ctap2.rs#L1100-L1112)?

**Comment by szszszsz** [comment] 2022-12-19 15:29
> Looking [here](https://github.com/Nitrokey/fido-authenticator/blob/main/src/ctap2.rs#L786), it seems the counter is decremented every time, no matter if the current PIN is correct or not (assuming I'm looking in the right place).

Hi!
Always decrementing is by design. It covers timing attacks with power analysis.
Certainly this should not behave as you have encountered though.

**Comment by robin-nitrokey** [comment] 2023-07-10 14:59
Should be fixed by https://github.com/Nitrokey/fido-authenticator/pull/28.

**Closed** 2024-05-23 13:08 UTC
Labels: bug
